[package]
name = "brainlift"
version = "0.1.0"
authors = ["Zhuowei Zhang <zhuowei@worthdoingbadly.com>"]
edition = "2018"

[dependencies]
cranelift-codegen = "0.37.0"
cranelift-module = "0.37.0"
cranelift-faerie = "0.37.0"
cranelift-frontend = "0.37.0"
target-lexicon = "0.4.0"
